### ISSUE TITLE
Apache Kudu 1.10.0 rpm build

### ISSUE THREAD

**Issue by lightsailpro** [MartinWeindel/kudu-rpm#1]
When will the Apache Kudu 1.10.0 rpm be available for download? From this page https://kudu.apache.org/docs/release_notes.html, 1.10.0 has been released. Thanks.

**Comment by MartinWeindel** [comment]
Thanks for triggering. New rpm will be available in a few days.

**Comment by lightsailpro** [comment]
Awesome. Thanks a lot.

**Comment by MartinWeindel** [comment]
Just released v1.10.0-1.
