### ISSUE TITLE
is there an available kudu-client for kudu1.10.0

### ISSUE THREAD

**Issue by JavisPeng** [MartinWeindel/kudu-rpm#3]
where i install kudu-python, I got the error message:
`  Cannot find installed kudu client.`

maybe I can use the kudu-client-1.4.0 from http://archive.cloudera.com/kudu/redhat/7/x86_64/kudu/cloudera-kudu.repo, but it is too older to stay stable for kudu1.10.0

**Comment by MartinWeindel** [comment]
Please ask the Kudu community, this project is only about building a RPM.
https://kudu.apache.org/community.html
